apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-e3wo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-e3wo
    app.kubernetes.io/part-of: tkrw-pr714-0075-0045-app
  name: devfile-sample-e3wo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-e3wo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-e3wo
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0045-tenant/tkrw-pr714-0075-0045-app/devfile-sample-e3wo@sha256:2f7157845a3e69e7b25f072fc5d75447d722d8dab0c2e3033f73c10807b4bb54
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
